name: Angular CI/CD

on: 
  push:
    branches: [ master ]

jobs:
  setup-test-build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Install Angular CLI
        run: npm install -g @angular/cli
      
      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test --watch=false --browsers=ChromeHeadless
      
      - name: Build
        run: npm build --prod

      - name: Deploy to GitHubPages
        run: |
          cd dist/angular-dog-display-01

          git init

          git config user.name = "${{ github.actor }}"
          git config user.email = "${{ github.actor }}@users.noreply.github.com"


          git add .
          git commit -m "Deploy to gh-pages"

          # Add the github repository as a remote
          git remote add gh-token "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"

          # Force push from the build/web folder in the current gh-actions runner environment
          # to the repo's gh-pages branch. (All previous history on the gh-pages
          # branch will be lost, since we are overwriting it.)
          # This is ok since github is not a version control system for builds but a version control system for code
          git push gh-token HEAD:gh-pages --force

      
